#!/bin/bash



read -p "Enter the file name: " file_name



touch $file_name



echo "#!/bin/bash" > $file_name



vi $file_name



git add .



git commit -m '0x01-variables_if_else_while'



git push


